import React from 'react';
/*------------- Table Data used on Coupon Screen Start --------------------*/
module.exports = {
  data: [
    [
      {
        id: 1,
        allCouponData: 'FSQ45WH1',
        isActive: true,
        amount: 10,
        expirationDate: '10/27/2020',
        minSpend: 20,
        maxSpend: 100,
        maxUsagePerCoupon: 2,
        maxUsagePerUser: 1,
        isUsedWithOtherCoupons: true,
        isUsedWithSaleItems: true,
        availableProductArr: [1, 2, 3],
        availableCategoryArr: [1],
        couponTypeId: 1,
      },
    ],
    [
      {
        id: 2,
        allCouponData: 'FSQ45WH2',
        isActive: true,
        amount: 20,
        expirationDate: '10/29/2020',
        minSpend: 15,
        maxSpend: 30,
        maxUsagePerCoupon: '',
        maxUsagePerUser: '',
        isUsedWithOtherCoupons: false,
        isUsedWithSaleItems: false,
        availableProductArr: [1],
        availableCategoryArr: [1],
        couponTypeId: 2,
      },
    ],
    [
      {
        id: 3,
        allCouponData: 'FSQ45WH3',
        isActive: false,
        amount: 17,
        expirationDate: '10/30/2020',
        minSpend: 10,
        maxSpend: 40,
        maxUsagePerCoupon: 3,
        maxUsagePerUser: 1,
        isUsedWithOtherCoupons: true,
        isUsedWithSaleItems: false,
        availableProductArr: [2],
        availableCategoryArr: [1],
        couponTypeId: 1,
      },
    ],
    [
      {
        id: 4,
        allCouponData: 'FSQ45WH4',
        isActive: false,
        amount: 17,
        expirationDate: '03/10/2020',
        minSpend: 10,
        maxSpend: 40,
        maxUsagePerCoupon: 3,
        maxUsagePerUser: 1,
        isUsedWithOtherCoupons: true,
        isUsedWithSaleItems: false,
        availableProductArr: [2],
        availableCategoryArr: [1],
        couponTypeId: 1,
      },
    ],
    [
      {
        id: 5,
        allCouponData: 'FSQ45WH5',
        isActive: true,
        amount: 50,
        expirationDate: '01/10/2020',
        minSpend: 30,
        maxSpend: 70,
        maxUsagePerCoupon: 1,
        maxUsagePerUser: 1,
        isUsedWithOtherCoupons: false,
        isUsedWithSaleItems: false,
        availableProductArr: [2, 3],
        availableCategoryArr: [1],
        couponTypeId: 2,
      },
    ],
    [
      {
        id: 6,
        allCouponData: 'FSQ45WH6',
        isActive: true,
        amount: 35,
        expirationDate: '10/10/2020',
        minSpend: 30,
        maxSpend: 100,
        maxUsagePerCoupon: '',
        maxUsagePerUser: '',
        isUsedWithOtherCoupons: true,
        isUsedWithSaleItems: true,
        availableProductArr: [1, 2, 3],
        availableCategoryArr: [1],
        couponTypeId: 1,
      },
    ],
  ],
};
/*------------- Table Data used on Coupon Screen End --------------------*/
