const ActionType = {
  addPayPalAddress: 'ADD_PAYPAL_ADDRESS',
  addUserAddress: 'ADD_USER_ADDRESS',
  addMenuCategory: 'ADD_MENU_CATEGORY',
  editMenuCategory: 'EDIT_MENU_CATEGORY',
  deleteMenuCategory: 'DELETE_MENU_CATEGORY',
  addCoupon: 'ADD_COUPON',
  editCoupon: 'EDIT_COUPON',
  deleteCoupon: 'DELETE_COUPON',
  addMenuCategoryProduct: 'ADD_MENU_CATEGORY_PRODUCT',
  editMenuCategoryProduct: 'EDIT_MENU_CATEGORY_PRODUCT',
  deleteMenuCategoryProduct: 'DELETE_MENU_CATEGORY_PRODUCT',
  changePayPalAddresses: 'CHANGE_PAY_PAL_ADDRESS',
  changeUserAddress: 'CHANGE_USER_ADDRESS',
  hideActivityLoader: 'HIDE_ACTIVITY_LOADER',
  isLoggedIn: 'IS_LOGGEDIN',
  performAutoLogout: 'PERFORM_AUTO_LOGOUT',
  pushNewMessage: 'PUSH_NEW_MESSAGE',
  selectedLanguage: 'STORE_LANGUAGE',
  showActivityLoader: 'SHOW_ACTIVITY_LOADER',
  storeAuthToken: 'STORE_AUTH_TOKEN',
  storeCheckoutList: 'STORE_CHECKOUT_LIST',
  storeCouponList: 'STORE_COUPON_LIST',
  storeFAQs: 'STORE_FAQS',
  storeOrderedItemsData: 'STORE_ORDERED_ITEMS_DATA',
  storeMessages: 'STORE_MESSAGES',
  storeOrderedItem: 'STORE_ORDERED_ITEM',
  storeOrderHistoryList: 'STORE_ORDER_HISTORY_LIST',
  storeOrderRequestList: 'STORE_ORDER_REQUEST_LIST',
  storePayPalAddresses: 'STORE_PAY_PAL_ADDRESS',
  storeWithdrawHistoryList: 'STORE_WITHDRAW_HISTORY_LIST',
  storeSubItemData: 'STORE_SUB_ITEM_DATA',
  storeUserAddress: 'STORE_USER_ADDRESS',
  storeUserInfo: 'STORE_USER_INFO',
  storeUserReviewList: 'STORE_USER_REVIEW_LIST',
  toggleCategoryIsActive: 'TOGGLE_CATEGORY_IS_ACTIVE',
  toggleCouponIsActive: 'TOGGLE_COUPON_IS_ACTIVE',
  toggleProductIsActive: 'TOGGLE_PRODUCT_IS_ACTIVE',
  updateAppFirstLaunchToFalse: 'UPDATE_APP_FIRST_LAUNCH_TO_FALSE',
  updateInternetStatus: 'UPDATE_INTERNET_STATUS',
  updateOrderedItemsStatus: 'UPDATE_ORDERED_ITEMS_STATUS',
};

export default ActionType;
