const ActionType = {
  addPayPalAddress: 'ADD_PAYPAL_ADDRESS',
  addUserAddress: 'ADD_USER_ADDRESS',
  changePayPalAddresses: 'CHANGE_PAY_PAL_ADDRESS',
  changeUserAddress: 'CHANGE_USER_ADDRESS',
  hideActivityLoader: 'HIDE_ACTIVITY_LOADER',
  isLoggedIn: 'IS_LOGGEDIN',
  performAutoLogout: 'PERFORM_AUTO_LOGOUT',
  pushNewMessage: 'PUSH_NEW_MESSAGE',
  selectedLanguage: 'STORE_LANGUAGE',
  showActivityLoader: 'SHOW_ACTIVITY_LOADER',
  storeAuthToken: 'STORE_AUTH_TOKEN',
  storeCheckoutList: 'STORE_CHECKOUT_LIST',
  storeCurrentOrder: 'STORE_CURRENT_ORDER',
  storeFAQs: 'STORE_FAQS',
  storeHasStartedRoute: 'STORE_HAS_STARTED_ROUTE',
  storeHasPickedUpFood: 'STORE_HAS_PICKED_UP_FOOD',
  storeIsGoingToCustomer: 'STORE_IS_GOING_TO_CUSTOMER',
  storeDeliveryConfirmation: 'STORE_DELIVERY_CONFIRMATION',
  storeOrderedItemsData: 'STORE_ORDERED_ITEMS_DATA',
  storeMessages: 'STORE_MESSAGES',
  storeOrderedItem: 'STORE_ORDERED_ITEM',
  storeOrderHistoryList: 'STORE_ORDER_HISTORY_LIST',
  storeOrderRequestList: 'STORE_ORDER_REQUEST_LIST',
  storePayPalAddresses: 'STORE_PAY_PAL_ADDRESS',
  storeRequestedPreview: 'STORE_REQUESTED_PREVIEW',
  storeWithdrawHistoryList: 'STORE_WITHDRAW_HISTORY_LIST',
  storeSubItemData: 'STORE_SUB_ITEM_DATA',
  storeUserAddress: 'STORE_USER_ADDRESS',
  storeUserInfo: 'STORE_USER_INFO',
  updateAcceptingOrderStatus: 'UPDATE_ACCEPTING_ORDER_STATUS',
  updateAppFirstLaunchToFalse: 'UPDATE_APP_FIRST_LAUNCH_TO_FALSE',
  updateInternetStatus: 'UPDATE_INTERNET_STATUS',
  updateOrderedItemsStatus: 'UPDATE_ORDERED_ITEMS_STATUS',
};

export default ActionType;
