const Routes = {
  //All Screens
  AddCardDetails: 'AddCardDetails',
  AddNewPaypal: 'AddNewPaypal',
  AddPayoutMethods: 'AddPayoutMethods',
  BikeRegistrationScreen: 'BikeRegistrationScreen',
  CarRegistrationScreen: 'CarRegistrationScreen',
  ChangePassword: 'ChangePassword',
  ChatScreen: 'ChatScreen',
  ChooseLanguage: 'ChooseLanguage',
  ChooseRegistrationType: 'ChooseRegistrationType',
  CompanyInformation: 'CompanyInformation',
  CreateAccountSlideshow: 'CreateAccountSlideshow',
  CreditCardSettings: 'CreditCardSettings',
  CurrentOrderScreen: 'CurrentOrderScreen',
  DriversLicense: 'DriversLicense',
  FAQScreen: 'FAQScreen',
  Delivery: 'Delivery',
  ForgotPassword: 'ForgotPassword',
  LookingByMapScreen: 'LookingByMapScreen',
  MyWalletHomeScreen: 'MyWalletHomeScreen',
  NotificationsHomeScreen: 'NotificationsHomeScreen',
  OTPVerification: 'OTPVerification',
  OnlineSupport: 'OnlineSupport',
  OrderDetailScreen: 'OrderDetailScreen',
  Other: 'Other',
  PersonalInformation: 'PersonalInformation',
  PrivacyPolicy: 'PrivacyPolicy',
  Registration: 'Registration',
  SendOTPVerification: 'SendOTPVerification',
  Settings: 'Settings',
  SurrenderActScreen: 'SurrenderActScreen',
  TermsOfUse: 'TermsOfUse',
  VehicleRegistrationHomeScreen: 'VehicleRegistrationHomeScreen',
  Welcome: 'Welcome',
  WireTransfer: 'WireTransfer',
  WithdrawHistoryScreen: 'WithdrawHistoryScreen',
  WizardHomeScreen: 'WizardHomeScreen',

  //Tab Menus
  DeliveryTabMenu: 'DeliveryTabMenu',
  NotificationsTabMenu: 'NotificationsTabMenu',
  OrderHistoryTabMenu: 'OrderHistoryTabMenu',
  ProfileTabMenu: 'ProfileTabMenu',

  //Home Screens for Modular Menus
  DeliveryHomeScreen: 'DeliveryHomeScreen',
  FavoriteProductsHomeScreen: 'FavoriteProductsHomeScreen',
  OrderHistoryHomeScreen: 'OrderHistoryHomeScreen',
  PaymentMethodsHomeScreen: 'PaymentMethodsHomeScreen',
  ProfileHomeScreen: 'ProfileHomeScreen',
  SupportHomeScreen: 'SupportHomeScreen',

  //Module Menus
  DeliveryModuleMenu: 'DeliveryModuleMenu',
  NotificationsModuleMenu: 'NotificationsModuleMenu',
  OrderHistoryModuleMenu: 'OrderHistoryModuleMenu',
  OtherModuleMenu: 'OtherModuleMenu',
  PaymentMethodModuleMenu: 'PaymentMethodModuleMenu',
  ProfileModuleMenu: 'ProfileModuleMenu',
  SettingModuleMenu: 'SettingModuleMenu',
  SupportModuleMenu: 'SupportModuleMenu',
  VehicleRegistrationModuleMenu: 'VehicleRegistrationModuleMenu',
  WizardModuleMenu: 'WizardModuleMenu',
};

export default Routes;
